#!/usr/bin/env python

import RPi.GPIO as GPIO
import time
import sys
from hx711 import HX711


hx = HX711(5, 6)
hx.set_reading_format("LSB", "MSB")
hx.set_reference_unit(1701)
hx.set_offset(int(sys.argv[1]))

val = hx.get_weight(5)
print val

GPIO.cleanup()
